### ISSUE TITLE
bpSyscall  and execIndirectSyscall missing function body

### ISSUE THREAD

**Issue by JingRuoMing** [scriptchildie/gohellsgate#1]
I pulled gohellsgate. problem compiling example
`C:\Users\user\go\pkg\mod\github.com\scriptchildie\gohellsgate@v0.9.1\syscalls.go:88:6: missing function body
C:\Users\user\go\pkg\mod\github.com\scriptchildie\gohellsgate@v0.9.1\syscalls.go:109:6: missing function body`
Is it me, compile problem?

**Comment by scriptchildie** [comment]
can you please send a sample code ? Also what architecture is this running on ? The library only works for windows x64

**Comment by JingRuoMing** [comment]
Code is your example.
Runs on x86 architecture, is Windows 10.
I didn't expect to reply to messages so quickly

**Comment by scriptchildie** [comment]
it won't run on x86 it's only compatible with x64 at the moment. I am working on adding functionality with wow64 and 32-bit soon.

**Comment by JingRuoMing** [comment]
That was it, now it's solved,
Just change it to GOARCH = amd64
`set GOARCH=amd64`
Actually, it's still my compile problem, sorry
